### PR TITLE
Remove unnecessary locks in keeperStore

### LINKED ISSUE #239: Remove unnecessary locks in KeeperStore
### Description

Because the current raft processes requests in a single-threaded serial manner, we can remove some unnecessary locks in the node and nodemap.

### PR DESCRIPTION
**Pull request by lzydmxy**
### Which issues of this PR fixes:

This PR try to fix #239

### Change log:

- remove node's lock
- remove nodeMap's lock

Slightly peformance improve
```
# before
thread_size,tps,avgRT(microsecond),TP90(microsecond),TP99(microsecond),TP999(microsecond),failRate
200,97658,2064.0,2900.0,3700.0,5200.0,0.0
200,97157,2066.0,2900.0,3800.0,6000.0,0.0
# after
thread_size,tps,avgRT(microsecond),TP90(microsecond),TP99(microsecond),TP999(microsecond),failRate
200,100083,2014.0,3000.0,3800.0,5500.0,0.0
200,99541,2025.0,3000.0,3700.0,5200.0,0.0
```

### CODE REVIEW

**Comment by lzydmxy** [comment]
@JackyWoo Failed for TEST(RaftPerformance, machineCreateThread), should i remove it ? Since `RK::ConcurrentMap` is no longer thread-safe

**Comment by JackyWoo** [comment]
We can make it single thread.

**Comment by lzydmxy** [comment]
> We can make it single thread. Also let's rename `ConcurrentMap `.

okay

**Comment by lzydmxy** [comment]
After all snapshot load faster than  before.

**Review by JackyWoo — APPROVED** [review]

**Pull request merged**
